### ISSUE TITLE
Error unitialized constant Logdna

### ISSUE THREAD

**Issue by andreleoni** [logdna/rails#4]
Hello I'm getting the follow error when I put my config on `config.logger` of my app:
`uninitialized constant Logdna (NameError)`

The complete traceback:

```
Traceback (most recent call last):
	63: from bin/rails:3:in `<main>'
	62: from bin/rails:3:in `load'
	61: from /website/bin/spring:15:in `<top (required)>'
	60: from /website/bin/spring:15:in `require'
	59: from /usr/local/bundle/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	58: from /usr/local/bundle/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	57: from /usr/local/bundle/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	56: from /usr/local/bundle/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	55: from /usr/local/bundle/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	54: from /usr/local/bundle/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	53: from /usr/local/bundle/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	52: from /website/bin/rails:9:in `<top (required)>'
	51: from /website/bin/rails:9:in `require'
	50: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
	49: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/command.rb:44:in `invoke'
	48: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/command/base.rb:63:in `perform'
	47: from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	46: from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	45: from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	44: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `perform'
	43: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `tap'
	42: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:135:in `block in perform'
	41: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:42:in `start'
	40: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
	39: from /usr/local/bundle/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
	38: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:24:in `app'
	37: from /usr/local/bundle/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
	36: from /usr/local/bundle/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	35: from /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
	34: from /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
	33: from /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
	32: from config.ru:in `<main>'
	31: from config.ru:in `new'
	30: from /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
	29: from /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
	28: from config.ru:3:in `block in <main>'
	27: from /website/config/environment.rb:5:in `<top (required)>'
	26: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
	25: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
	24: from /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	23: from /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	22: from /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	21: from /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
	20: from /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
	19: from /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	18: from /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	17: from /usr/local/lib/ruby/2.5.0/tsort.rb:415:in `call'
	16: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/initializable.rb:48:in `tsort_each_child'
	15: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/initializable.rb:48:in `each'
	14: from /usr/local/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	13: from /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	12: from /usr/local/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	11: from /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	10: from /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	 9: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
	 8: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
	 7: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
	 6: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/engine.rb:599:in `block in <class:Engine>'
	 5: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/engine.rb:599:in `each'
	 4: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
	 3: from /website/config/environments/development.rb:3:in `<top (required)>'
	 2: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/railtie.rb:211:in `configure'
	 1: from /usr/local/bundle/gems/railties-5.1.6/lib/rails/railtie.rb:211:in `instance_eval'
/website/config/environments/development.rb:50:in `block in <top (required)>': uninitialized constant Logdna (NameError)
```

**Comment by andreleoni** [comment]
I, [2018-06-23T04:05:41.086147 #2133]  INFO -- sentry: ** [Raven] Raven 2.7.3 configured not to capture errors: Not configured to send/capture in environment 'development'
DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. (called from <module:Website> at /website/config/application.rb:153)
=> Booting Puma
=> Rails 5.1.6 application starting in development 
=> Run `rails server -h` for more startup options

```
From: /website/config/environments/development.rb @ line 48 :

    43:     :level => ['TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL'],
    44:     :env => "PRODUCTION",
    45:     :meta => {:once => {:first => "nested1", :another => "nested2"}}
    46:   }
    47:   binding.pry
 => 48:   config.logger = Logdna::RailsLogger.new(******, options)
    49:   config.webpacker.check_yarn_integrity = false
    50: 
    51:   # Raise an error on page load if there are pending migrations.
    52:   config.active_record.migration_error = :page_load
    53: 
```
[1] pry(#<Website::Application>)> Logdna
NameError: uninitialized constant Logdna
from (pry):1:in `block in <top (required)>'

**Comment by beefcheeks** [comment]
@andreleoni thanks for your patience. Would you mind pasting the output of these commands? Be sure to run it inside your rails project directory.
```
gem list logdna
gem list logdna-rails
```

Thanks in advance for your patience.

**Comment by Deekor** [comment]
I am also having this issue

**Comment by Deekor** [comment]
For some reason version `.0.0.5` was installed. Updating the gem got past this error
